Booklay/booklay-front

src/main/java/com/nhnacademy/booklay/booklayfront/controller/CategoryAdminController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/PageResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/category/request/CategoryCreateRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/category/request/CategoryUpdateRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/category/response/CategoryResponse.java, src/main/resources/templates/category/createForm.html, src/main/resources/templates/category/detail.html, src/main/resources/templates/category/list.html
/get admin/categories : 카테고리 리스트
/get admin/categories/create : 카테고리 생성 폼 
/post admin/categories: 카테고리 생성 요청
/get admin/categories/delete/{카테고리 번호} : 카테고리 삭제
=> 카테고리 등록/삭제 컨트롤러 및 약식 html 추가

src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/product/AdminAuthorController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/member/response/MemberForAuthorResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/author/request/CreateAuthorRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/author/response/RetrieveAuthorResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/request/CreateProductBookRequest.java, src/main/resources/templates/admin/product/adminAuthor.html
=> 상품- 작가 조회, 생성 프론트 제작

src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/coupon/CouponAdminFrontController.java, src/main/resources/templates/fragments/adminnavbar.html
Coupon 서버 분리하면서, Coupon Controller 쪽 url 수정했습니다.
=> fix: CouponAdminFrontController prefix, url 수정

src/main/java/com/nhnacademy/booklay/booklayfront/controller/member/MemberController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/delivery/response/DeliveryDestinationRetrieveResponse.java, src/main/resources/templates/mypage/member/memberAddress.html, src/main/resources/templates/mypage/member/memberDetail.html
mypage의 member address view 페이지 작성, address retrieve controller 로직 구현
=> feat: member 주소목록 페이지와 controller 작성

pom.xml, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/product/AdminAuthorController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/product/AdminProductController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/product/AdminTagController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/product/ProductController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/author/request/CreateAuthorRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/author/response/RetrieveAuthorResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/request/CreateProductBookFormData.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/request/CreateProductBookJson.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/request/CreateProductBookRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/tag/request/CreateDeleteTagProductRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/tag/request/CreateTagRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/tag/request/UpdateTagRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/tag/response/RetrieveTagResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/tag/response/TagProductResponse.java, src/main/resources/static/js/productBookRegister.js, src/main/resources/templates/admin/product/adminAuthor.html, src/main/resources/templates/admin/product/adminTag.html, src/main/resources/templates/admin/product/createProductBookForm.html, src/main/resources/templates/admin/product/productMainManage.html, src/main/resources/templates/admin/product/productTagConnector.html, src/main/resources/templates/product/productDetailView.html, src/test/java/com/nhnacademy/booklay/booklayfront/controller/MemberControllerTest.java
백앤드에서 오브젝트 스토리지에 올리는거 구현해야 합니다...
=> 상품에 태그 등록/삭제, 상품 등록시 이미지와 json 동시 전송 구현

src/main/java/com/nhnacademy/booklay/booklayfront/config/WebConfig.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/product/AdminAuthorController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/product/AdminProductController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/product/AdminTagController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/product/ProductBoardController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/product/productBoardController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/member/response/MemberForAuthorResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/DeleteByIdRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/author/request/CreateAuthorRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/author/request/UpdateAuthorRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/author/response/RetrieveAuthorResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/request/CreateProductBookFormData.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/request/CreateProductBookJson.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/request/CreateProductBookRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/tag/request/CreateDeleteTagProductRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/tag/request/CreateTagRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/tag/request/UpdateTagRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/tag/response/RetrieveTagResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/tag/response/TagProductResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/wishlist/request/CreateWishlistRequest.java, src/main/resources/static/css/author.css, src/main/resources/static/js/productBookRegister.js, src/main/resources/templates/admin/product/adminAuthor.html, src/main/resources/templates/admin/product/adminAuthorProductView.html, src/main/resources/templates/admin/product/adminTag.html, src/main/resources/templates/admin/product/productTagConnector.html, src/main/resources/templates/product/productDetailView.html
=> 태그 구현 종료, 작가 삭제 구현 

src/main/resources/templates/admin/category/listView.html, src/main/resources/templates/fragments/pageFooter.html
=> style: 버튼 스타일 변경

src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/member/MemberAdminController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/member/MemberController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/mypage/PointHistoryController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/member/response/PointCouponRetrieveResponse.java, src/main/resources/templates/admin/category/listView.html, src/main/resources/templates/admin/member/memberList.html, src/main/resources/templates/fragments/membernavbar.html, src/main/resources/templates/mypage/member/memberAddressList.html, src/main/resources/templates/mypage/member/memberPointCouponList.html, src/main/resources/templates/mypage/member/memberPointList.html
포인트 쿠폰 조회 페이지와 로직 구현
회원 리스트 조회 페이지 일부 구현 (보완 필요)
=> feat: 포인트 쿠폰 조회 페이지 구현, 회원리스트 조회 페이지 일부 구현

src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/product/AdminProductController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/product/AdminTagController.java
=> hotfix : / 매핑 오류 수정

src/main/java/com/nhnacademy/booklay/booklayfront/auth/jwt/TokenUtils.java, src/main/java/com/nhnacademy/booklay/booklayfront/config/SecurityConfig.java, src/main/java/com/nhnacademy/booklay/booklayfront/filter/JwtAuthenticationFilter.java, src/test/java/com/nhnacademy/booklay/booklayfront/controller/cart/CartControllerTest.java, src/test/java/com/nhnacademy/booklay/booklayfront/coupon/controller/CouponAdminFrontControllerTest.java, src/test/java/com/nhnacademy/booklay/booklayfront/coupon/controller/CouponMemberFrontControllerTest.java
스케일 아웃 환경에서 인증 동작하도록 JwtAuthenticationFilter에서 인증 로직 실행
=>  jwtAuthenticationFilter 추가

pom.xml, src/main/java/com/nhnacademy/booklay/booklayfront/BooklayFrontApplication.java, src/main/java/com/nhnacademy/booklay/booklayfront/auth/AuthenticationServerProxy.java, src/main/java/com/nhnacademy/booklay/booklayfront/auth/UsernamePasswordAuthenticationProvider.java, src/main/java/com/nhnacademy/booklay/booklayfront/auth/aspect/MemberAspect.java, src/main/java/com/nhnacademy/booklay/booklayfront/auth/constant/Roles.java, src/main/java/com/nhnacademy/booklay/booklayfront/auth/filter/InitialAuthenticationFilter.java, src/main/java/com/nhnacademy/booklay/booklayfront/auth/filter/JwtAuthenticationFilter.java, src/main/java/com/nhnacademy/booklay/booklayfront/auth/interceptor/JwtAddInterceptor.java, src/main/java/com/nhnacademy/booklay/booklayfront/auth/jwt/TokenUtils.java, src/main/java/com/nhnacademy/booklay/booklayfront/config/SecurityConfig.java, src/main/java/com/nhnacademy/booklay/booklayfront/config/WebConfig.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/member/MemberController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/common/MemberInfo.java
``` java
@GetMapping("/{memberNo}")
public String retrieveMemberDetail(@PathVariable Long memberNo, Model model, MemberInfo memberInfo)
```
위와 같이 컨트롤러 파라미터에 MemberInfo 선언만 해주면 로그인한 회원 정보가 알아서 들어옵니다.
=> AOP를 통한 로그인 회원 정보 받아오는 기능 구현

src/main/resources/templates/admin/coupon/issue/issueHistoryView.html
=> fix: footer 제외

src/main/java/com/nhnacademy/booklay/booklayfront/config/WebConfig.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/WebControllerAdvice.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/product/ProductDisplayController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/storage/ObjectFileStorageController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/response/RetrieveProductBookForUpdateResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/response/RetrieveProductSubscribeForUpdateResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/wishlist/request/CreateDeleteWishlistAndAlarmRequest.java, src/main/resources/templates/admin/product/updateProductBookForm.html, src/main/resources/templates/admin/product/updateProductSubscribeForm.html, src/main/resources/templates/fragments/navbar.html, src/main/resources/templates/fragments/topbar.html, src/main/resources/templates/product/detail.html, src/main/resources/templates/product/shop.html
=> 상품 검색 수정 DTO queryDsl 적용

src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/coupon/CouponAdminFrontController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/coupon/CouponZoneController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/Coupon.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/CouponAddRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/CouponDetail.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/restapimodelsetting/CouponRestApiModelSettingService.java, src/main/resources/templates/admin/coupon/couponUpdateForm.html, src/main/resources/templates/admin/coupon/createCouponForm.html, src/main/resources/templates/admin/coupon/template/templateDetailView.html, src/main/resources/templates/mypage/coupon/detailView.html, src/test/java/com/nhnacademy/booklay/booklayfront/coupon/controller/CouponAdminFrontControllerTest.java, src/test/java/com/nhnacademy/booklay/booklayfront/coupon/controller/CouponMemberFrontControllerTest.java
=> feat:coupon update

pom.xml, src/main/java/com/nhnacademy/booklay/booklayfront/config/SecurityConfig.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/member/MemberAdminController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/member/MemberController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/ControllerStrings.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/member/request/MemberCreateRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/member/response/MemberGradeChartRetrieveResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/member/MemberService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/member/MemberServiceImpl.java, src/main/resources/application.yml, src/main/resources/templates/admin/member/memberChart.html, src/test/java/com/nhnacademy/booklay/booklayfront/controller/cart/CartControllerTest.java, src/test/java/com/nhnacademy/booklay/booklayfront/coupon/controller/CouponAdminFrontControllerTest.java, src/test/java/com/nhnacademy/booklay/booklayfront/coupon/controller/CouponMemberFrontControllerTest.java
회원가입 시 비밀번호 BCrypt 적용
생성자로 비밀번호 바꿔서 return 하려고 했으나 unique construct 이슈로 setter 적용했습니다.
좋은 아이디어 있으면 추천 부탁드립니다.
=> feat: 회원가입 시 비밀번호 BCrypt 적용

src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/category/CategoryAdminController.java, src/main/resources/templates/admin/category/createForm.html, src/main/resources/templates/admin/category/list.html, src/main/resources/templates/admin/category/updateForm.html, src/main/resources/templates/thymeleaf/fragments/admin_side.html
=> feat: 카테고리 관리 페이지 UI 수정

src/main/java/com/nhnacademy/booklay/booklayfront/controller/search/SearchController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/response/ProductAllInOneResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/response/ProductDetailResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/response/ProductResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/response/SubscribeResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/tag/response/RetrieveTagResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/search/SearchService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/search/impl/SearchServiceImpl.java, src/main/resources/templates/thymeleaf/fragments/search_box.html
=> 검색 결과 리턴 타입 변경, 검색 요청 유지

src/main/java/com/nhnacademy/booklay/booklayfront/auth/AuthenticationServerProxy.java, src/main/java/com/nhnacademy/booklay/booklayfront/auth/dto/RefreshTokenRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/auth/filter/JwtAuthenticationFilter.java, src/main/java/com/nhnacademy/booklay/booklayfront/auth/handler/CustomLoginFailureHandler.java, src/main/java/com/nhnacademy/booklay/booklayfront/config/SecurityConfig.java, src/main/java/com/nhnacademy/booklay/booklayfront/config/WebConfig.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/member/response/MemberResponse.java, src/main/resources/application.yml, src/main/resources/templates/member/loginForm.html
=> Access Token Refresh + 차단, 탈퇴회원 로직 추가

src/main/java/com/nhnacademy/booklay/booklayfront/controller/mypage/PointHistoryController.java, src/main/resources/templates/mypage/member/memberAddressList.html, src/main/resources/templates/mypage/member/memberDetail.html, src/main/resources/templates/mypage/member/memberGradeList.html, src/main/resources/templates/mypage/member/memberPointCouponList.html, src/main/resources/templates/mypage/member/memberPointPresent.html
=> fix: mypage의 point page 수정

src/main/java/com/nhnacademy/booklay/booklayfront/config/SecurityConfig.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/coupon/CouponAdminFrontController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/coupon/CouponIssueAdminFrontController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/coupon/CouponZoneAdminController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/coupon/CouponZoneController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/CouponAddRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/CouponDetail.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/request/CouponZoneCreateRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/response/CouponZoneRetrieveResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/grade/Grade.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/ObjectFileService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/coupon/CouponAdminService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/coupon/CouponAdminServiceImpl.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/restapimodelsetting/ProductRestApiModelSettingService.java, src/main/resources/static/js/coupon/couponPopup.js, src/main/resources/templates/admin/coupon/couponImageUpdateForm.html, src/main/resources/templates/admin/coupon/couponUpdateForm.html, src/main/resources/templates/admin/coupon/couponZone/couponZoneAddForm.html, src/main/resources/templates/admin/coupon/couponZone/couponZoneList.html, src/main/resources/templates/admin/coupon/createCouponForm.html, src/main/resources/templates/admin/coupon/detailView.html, src/main/resources/templates/admin/coupon/empty.html, src/main/resources/templates/admin/coupon/issue/issueCouponToMemberForm.html, src/main/resources/templates/admin/coupon/issue/issueHistoryView.html, src/main/resources/templates/admin/coupon/listView.html, src/main/resources/templates/admin/coupon/popup/productPopup.html, src/main/resources/templates/coupon/couponZone.html, src/test/java/com/nhnacademy/booklay/booklayfront/coupon/controller/CouponAdminFrontControllerTest.java, src/test/java/com/nhnacademy/booklay/booklayfront/coupon/controller/CouponMemberFrontControllerTest.java
쿠폰존과 쿠폰의 테이블 변경으로 dto, 로직 변경했습니다.
그리고 짜잘한 버그들도...
=> feat: 쿠폰존, 쿠폰 변경

src/main/java/com/nhnacademy/booklay/booklayfront/controller/mypage/ProductController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/product/ProductDisplayController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/response/RetrieveProductResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/wishlist/request/CreateDeleteWishlistAndAlarmRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/wishlist/response/WishlistAndAlarmBooleanResponse.java, src/main/resources/templates/mypage/product/wishlist.html, src/main/resources/templates/product/view.html, src/main/resources/templates/thymeleaf/fragments/profile_side.html
=> 위시리스트, 찜 기능 개발

src/main/java/com/nhnacademy/booklay/booklayfront/config/SecurityConfig.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/WebControllerAdvice.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/coupon/CouponAdminFrontController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/coupon/CouponIssueAdminFrontController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/coupon/CouponZoneAdminController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/coupon/CouponZoneController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/coupon/CouponZoneRestController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/request/CouponZoneIsBlindRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/response/CouponHistoryResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/response/CouponIssueResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/response/CouponMemberResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/response/CouponZoneIsBlindResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/response/CouponZoneRetrieveResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/grade/Grade.java, src/main/java/com/nhnacademy/booklay/booklayfront/exception/LoginEssentialException.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/restapimodelsetting/CouponRestApiModelSettingService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/restapimodelsetting/CouponZoneRestApiModelSettingService.java, src/main/resources/static/js/coupon/couponIssue.js, src/main/resources/templates/admin/coupon/couponZone/couponZoneAddForm.html, src/main/resources/templates/admin/coupon/couponZone/couponZoneList.html, src/main/resources/templates/admin/coupon/couponZone/couponZoneUpdateForm.html, src/main/resources/templates/admin/coupon/issue/issueHistoryView.html, src/main/resources/templates/admin/coupon/popup/memberPopup.html, src/main/resources/templates/coupon/couponZone.html
사용자의 쿠폰 발급 기능 추가.
발급 후 요청에 대한 응답 값 보이기 완료.
리팩토링 **필요**
=> Feat : coupon zone

src/main/java/com/nhnacademy/booklay/booklayfront/controller/BaseController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/IndexController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/search/SearchController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/common/MemberInfo.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/product/product/response/ProductAllInOneResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/search/request/SearchCategoryRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/search/request/SearchKeywordsRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/search/response/AuthorInfo.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/search/response/SearchPageResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/search/response/SearchProductResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/RestService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/search/SearchService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/search/impl/SearchServiceImpl.java, src/main/java/com/nhnacademy/booklay/booklayfront/utils/ControllerUtil.java, src/main/resources/templates/product/displayV2.html, src/main/resources/templates/thymeleaf/fragments/main_menu.html, src/main/resources/templates/thymeleaf/fragments/main_top.html, src/main/resources/templates/thymeleaf/fragments/pagination.html, src/main/resources/templates/thymeleaf/fragments/search_box.html
제품 자체 키워드, 태그, 작가, 카테고리의 문자열 검색 기능과 카테고리 필터링 추가하였습니다.
현재 직접 등록된 카테고리에 대해서만 검색 가능하고, 상위 카테고리에 대한 검색도 추가할 예정입니다.
=> 엘라스틱 서치 검색 기능 추가

src/main/resources/static/js/member/memberBlockPopup.js, src/main/resources/templates/admin/member/memberBlockCancelForm.html, src/main/resources/templates/admin/member/memberBlockForm.html, src/main/resources/templates/mypage/member/memberAddressList.html, src/main/resources/templates/mypage/member/memberAddressUpdateForm.html, src/main/resources/templates/mypage/member/memberGradeList.html, src/main/resources/templates/mypage/member/memberPointCouponList.html, src/main/resources/templates/mypage/member/memberPointList.html
=> fix: 회원 차단 form 수정, 그 외 에러 수정

src/main/java/com/nhnacademy/booklay/booklayfront/controller/product/ProductDisplayController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/category/response/CategorySteps.java
ProductDisplayController 불요 코드 제거
=> CategorySteps DTO수정

src/main/java/com/nhnacademy/booklay/booklayfront/controller/IndexController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/product/ProductBoardController.java, src/main/resources/templates/main/main.html, src/main/resources/templates/product/view.html
elastic search 적용시키는법은 잘 모르겠어서 수정 해야 합니다.
=> 메인페이지 신간 추천 기능 구현

src/main/java/com/nhnacademy/booklay/booklayfront/controller/IndexController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/search/SearchController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/search/request/SearchIdRequest.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/IndexService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/search/SearchService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/search/impl/SearchServiceImpl.java, src/main/resources/templates/main/main.html, src/main/resources/templates/product/displayV2.html, src/main/resources/templates/thymeleaf/fragments/main_menu.html, src/main/resources/templates/thymeleaf/fragments/search_box.html
=> 메인화면 상품 추천 및 작가 번호, 태그 번호 검색 추가

src/main/java/com/nhnacademy/booklay/booklayfront/controller/mypage/PointHistoryController.java, src/main/resources/templates/member/register.html, src/main/resources/templates/mypage/member/memberPointCouponList.html, src/main/resources/templates/mypage/member/memberPointPresent.html
=> fix: 코드 리팩토링

src/main/resources/static/css/coupon/couponStyle.css, src/main/resources/templates/mypage/coupon/ownedCouponListView.html
=> fix: 쿠폰 조회 수정

src/main/java/com/nhnacademy/booklay/booklayfront/controller/member/MemberController.java, src/main/resources/static/js/member/memberUDPopup.js, src/main/resources/templates/mypage/member/memberUpdateForm.html
=> fix: 회원정보 수정 페이지 update

src/main/java/com/nhnacademy/booklay/booklayfront/config/SecurityConfig.java
=> Oauth 정보 수정

src/main/java/com/nhnacademy/booklay/booklayfront/dto/common/MemberInfo.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/member/response/MemberRetrieveResponse.java
- 버그있을수도 있음
- 버그날 경우 화이팅..
- 롤백해보고.. aop 잘 수정바람..
=> MemberInfo 권한, 등급  추가

src/main/java/com/nhnacademy/booklay/booklayfront/controller/WebControllerAdvice.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/coupon/CouponHistoryAdminFrontController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/coupon/CouponIssueAdminFrontController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/coupon/CouponZoneRestController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/member/MemberController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/response/CouponZoneTimeResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/response/MemberOwnedCouponResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/exception/CouponZoneTimeException.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/coupon/CouponZoneService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/restapimodelsetting/CouponRestApiModelSettingService.java, src/main/resources/static/css/coupon/couponStyle.css, src/main/resources/static/js/coupon/couponIssue.js, src/main/resources/static/js/coupon/couponPopup.js, src/main/resources/static/js/coupon/couponZoneDateSetting.js, src/main/resources/static/js/login.js, src/main/resources/templates/admin/coupon/couponUpdateForm.html, src/main/resources/templates/admin/coupon/couponZone/couponZoneAddForm.html, src/main/resources/templates/admin/coupon/issue/issueCouponToMemberForm.html, src/main/resources/templates/coupon/couponZone.html, src/main/resources/templates/member/loginForm.html, src/main/resources/templates/member/register.html, src/main/resources/templates/mypage/coupon/ownedCouponListView.html, src/main/resources/templates/mypage/member/memberAddressList.html, src/main/resources/templates/mypage/member/memberAddressRegisterForm.html, src/main/resources/templates/mypage/member/memberPointList.html, src/main/resources/templates/thymeleaf/fragments/profile_top.html, src/test/java/com/nhnacademy/booklay/booklayfront/coupon/controller/CouponAdminFrontControllerTest.java
쿠폰존에서 쿠폰 발급시 발급 기간 확인 추가 했습니다.
회원 쪽 뷰 수정했습니다.
회원가입 쿠폰 발급 기능 추가 했습니다.
sweetalert 추가했습니다.
=> feat: 쿠폰존 수정 및 뷰 디테일 수정

src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/member/MemberAdminController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/mypage/PointHistoryController.java, src/main/resources/static/js/member/pointHistoryPopup.js, src/main/resources/templates/admin/member/adminMemberPointList.html, src/main/resources/templates/admin/member/blockedMemberList.html, src/main/resources/templates/admin/member/memberBlockCancelForm.html, src/main/resources/templates/admin/member/memberList.html, src/main/resources/templates/member/register.html, src/main/resources/templates/mypage/member/memberAddressList.html, src/main/resources/templates/mypage/member/memberPointPresent.html, src/main/resources/templates/mypage/member/memberUpdateForm.html, src/main/resources/templates/mypage/member/pointCouponConvertForm.html
=> fix: admin의 point 조회 시 popup으로 띄움, 리팩토링

src/main/resources/static/css/owl.carousel.min.css, src/main/resources/static/js/mainCarousel.js, src/main/resources/static/js/owl.carousel.js, src/main/resources/static/js/owl.carousel.min.js, src/main/resources/templates/main/main.html
=> feat: main carousel

src/main/java/com/nhnacademy/booklay/booklayfront/controller/WebControllerAdvice.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/product/ProductDisplayController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/review/ReviewController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/coupon/ApiEntity.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/search/response/SearchPageResponse.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/ReviewService.java, src/main/resources/static/css/pointStar.css, src/main/resources/static/js/errorHandler/alertMessage.js, src/main/resources/templates/product/fragments/reviewList.html, src/main/resources/templates/product/fragments/reviewPagination.html, src/main/resources/templates/product/fragments/reviewRegister.html, src/main/resources/templates/product/view.html, src/main/resources/templates/thymeleaf/fragments/main_top.html, src/main/resources/templates/thymeleaf/fragments/profile_top.html, src/main/resources/templates/thymeleaf/layout/admin.html, src/main/resources/templates/thymeleaf/layout/blank.html, src/main/resources/templates/thymeleaf/layout/default.html, src/main/resources/templates/thymeleaf/layout/profile.html
=> 상품 리뷰 노출 정보 수정 및 검색 노출 일부 수정

src/main/java/com/nhnacademy/booklay/booklayfront/controller/WebControllerAdvice.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/IndexService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/search/impl/SearchServiceImpl.java
=> fix: 상품 노출 에러 수정

src/main/java/com/nhnacademy/booklay/booklayfront/controller/search/SearchController.java, src/main/java/com/nhnacademy/booklay/booklayfront/dto/search/request/SearchKeywordsRequest.java
=> fix: 검색 수행 로직 수정

src/main/java/com/nhnacademy/booklay/booklayfront/config/SecurityConfig.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/WebControllerAdvice.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/category/CategoryAdminController.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/category/CategoryService.java, src/main/resources/templates/thymeleaf/fragments/main_top.html
카테고리 생성 수정 삭제시 캐시 삭제하여 반영하게 끔 수정
=> feat: 카테고리 변경시 캐시 처리, 상품 정렬 순서 변경

src/main/resources/templates/admin/coupon/popup/couponPopup.html, src/main/resources/templates/order/popup/couponPopupForOrder.html
=> feat: coupon popup

src/main/java/com/nhnacademy/booklay/booklayfront/service/category/CategoryService.java
=> fix: 에러 처리 추가

src/main/java/com/nhnacademy/booklay/booklayfront/controller/board/NoticeBoardController.java
=> hotfix : 멤버 인포 추가

src/main/java/com/nhnacademy/booklay/booklayfront/controller/delivery/DeliveryDestinationController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/mypage/PointHistoryController.java, src/main/resources/templates/mypage/member/memberPointPresent.html
=> feat: 에러 메시지 출력

src/main/java/com/nhnacademy/booklay/booklayfront/controller/delivery/DeliveryDestinationController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/mypage/PointHistoryController.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/mypage/PointHistoryService.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/mypage/PointHistoryServiceImpl.java, src/main/resources/static/js/member/pointCouponPopup.js
point coupon 한 번 사용 후 같은 쿠폰 재사용을 막음
=> feat: point coupon 사용 시 재사용 막기 구현

src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/member/MemberAdminController.java, src/main/java/com/nhnacademy/booklay/booklayfront/controller/mypage/PointHistoryController.java, src/main/java/com/nhnacademy/booklay/booklayfront/service/mypage/PointHistoryServiceImpl.java
=> fix: refactoring

src/main/java/com/nhnacademy/booklay/booklayfront/controller/admin/AdminIndexController.java, src/main/resources/templates/admin/main.html, src/main/resources/templates/thymeleaf/fragments/admin_side.html
=> 쿠폰 템플릿, 회원통계 사이드바에서 주석처리
